version: "3.8"
services:
  product-service:
    depends_on:
      - itbooks-postgres
    image: "product-service"
    container_name: "product-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://itbooks-postgres:5432/itbooksdb_product
      - SPRING_PROFILES_ACTIVE=testdata
  
  config-service:
    image: "config-service"
    container_name: "config-service"
    ports:
      - 8888:8888
      - 9888:9888
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9888
 
  order-service:
    depends_on:
      - itbooks-postgres
    image: "order-service"
    container_name: "order-service"
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - ITBOOKS_PRODUCT_SERVICE_URI=http://product-service:9001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_R2DBC_URL=r2dbc:postgresql://itbooks-postgres:5432/itbooksdb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://itbooks-postgres:5432/itbooksdb_order
 
  edge-service:
    depends_on:
      - itbooks-redis
    image: "edge-service"
    container_name: "edge-service"
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8000
      - PRODUCT_SERVICE_URL=http://product-service:9001
      - ORDER_SERVICE_URL=http://order-service:9002
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_REDIS_HOST=itbooks-redis
 
 itbooks-postgres:
    image: "postgres:15"
    container_name: "itbooks-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  itbooks-redis:
    image: "redis:7.0"
    container_name: "itbooks-redis"
    ports:
      - 6379:6379
  
  itbooks-rabbitmq:
    image: rabbitmq:3.11
    container_name: itbooks-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
